#Profile which sets some quality settings (Recommended)
profile=high-quality

#Don't close the player after finishing the video
#keep-open=yes

#Start mpv with a % smaller resolution of your screen
#autofit=50%

#Turns on software rendering for screenshots
#Faster, but might lack stuff like HDR
screenshot-sw=yes

#Output format of screenshots
screenshot-format=png

#Same output bitdepth as the video
#Set it "no" if you want to save disc space
screenshot-high-bit-depth=no

#Output directory
screenshot-dir="~/Pictures/Screenshots/"

#Video output driver
#See: https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU
vo=gpu-next

#Called API
gpu-api=vulkan
